didi/mpx

packages/webpack-plugin/lib/index.js
packages/webpack-plugin/lib/wxml/wxml-loader.js

fix "Can't resolve module xx" when values of src in template files start with "/", which should be relative to project root

feat: Plugin option projectRoot

---

packages/webpack-plugin/lib/template-compiler/compiler.js

Fix illegally decoding entities in xml attributes when the template is serialized

Fix illegally decoding entities in xml attributes

---

packages/webpack-plugin/lib/template-compiler/compiler.js

Swan doesn't support an element has both the directive "for" and "if" Add a block and move "for" into it in this case.
Add __mpx_mode__ support in native mode

Shim "for" and "if" directive in Swan

---

packages/webpack-plugin/lib/template-compiler/compiler.js

Use case:
```html
<button open-type="share" wx:if="{{__mpx_mode__ !== 'swan'}}">Foo</button>
```

feature: add and remove dom attributes by mpx comment: @mpx-attrs

---

packages/webpack-plugin/lib/platform/template/wx/index.js
packages/webpack-plugin/test/platform/wx/template.spec.js

Fix swan trackBy wrong number loop warning and remove trackBy when key contains mustache templates

fix: swan trackBy 

---

packages/webpack-plugin/lib/index.js
packages/webpack-plugin/lib/template-compiler/compiler.js
packages/webpack-plugin/lib/template-compiler/index.js

Use example:
```javascript
new MpxWebpackPlugin({
mode: 'tt',
srcMode: 'wx',
// 统一处理不支持的属性
globalMpxAttrsFilter(info) {
const { __mpx_mode__, tagName, attrs } = info
let ret = {}
if (__mpx_mode__ === 'tt' && tagName === 'scroll-view') {
ret.remove = ['enable-back-to-top']
}
return ret // 返回同@mpx-attrs的平台下声明
},
}),
```

feat: globalMpxAttrsFilter

---

packages/api-proxy/src/web/api/route/index.js

vue router[ push、 replace]方法参数位置错误

修复转web时，redirectTo，navigateTo回调不生效的问题

---

packages/core/src/core/proxy.js

微信小程序里有很多用户定义data为null的情况，导致运行时报错。
``` javascript
createComponent({
data: {
data: null
}
})
```

fix: null has no 'hasOwnProperty'

---

packages/webpack-plugin/lib/runtime/stringify.wxs

头条小程序的sjs文件不支持forEach，但是支持map >_<

sjs of bytedance miniprogram do not support 'forEach'

---

packages/core/src/convertor/wxToWeb.js
packages/core/src/platform/builtInMixins/index.js
packages/core/src/platform/builtInMixins/pageOnResizeMixin.js
packages/core/src/platform/patch/web/lifecycle.js

* 增加 pageOnResizeMixin
* NOTSUPPORTS 数组中去除 onResize 过滤
* getBuiltInMixins 中增加 onResize 事件
* web lifecycle 中 pagehooks 增加 onResize 事件

小程序输出H5 支持 onResize 事件

---

docs-vuepress/api/global-api.md
docs-vuepress/guide/tool/ts.md
docs/ts.md

- 删除`getComputed`相关文档
- 删除`createApp`文档中`methods`相关描述
上述api最新版中已经删除了, 使用会报错.

remove unsupported api documents

---

packages/webpack-plugin/lib/template-compiler/compiler.js

the class indicating a node is set as a ref will be removed when processing class if the component tag starts with 'th-', causing corresponding ref can't be resolved. 
so ref class need to be restored.
在processClass时候，如果当前节点的tag是以th-开头的，class会被移动到ex-class。此时如果当前节点被设置为ref的时候，在组件初始化时候，ref就resolve不到。需要考虑在移动到ex-class之后，判断是否有ref class，有的话，需要恢复ref class

fix ref class

---

package.json
packages/core/@types/index.d.ts
packages/core/src/core/createStore.js
packages/core/src/index.js
packages/webpack-plugin/lib/template-compiler/compiler.js

feat(core/d.ts): support createStoreWithThis's type inference

---

packages/webpack-plugin/lib/template-compiler/compiler.js

如果template中格式化存在空格，则会编译成这样，导致内容为空
```javascript
{
"computed": {
_t1() {
return 
$t('xxx')
}
}
}
```

fix: 修复i18n注入computed 表达式异常

---

packages/core/@types/index.d.ts
packages/core/@types/mpx-store.d.ts

`createActionsWithThis` 增加 actions 依赖，使拆分 actions 更加便捷。
删除 `CompatibleDispatch` 中的兼容代码，后续不再在框架层面主动兼容 `createStoreWithThis` 和 `createStore`，如果用户需要，可自行对 `CompatibleDispatch` 作声明合并操作。
例：
```ts
declare module MpxStore {
interface CompatibleDispatch {
dispatch(type: string, ...payload: any[]): any
commit(type: string, ...payload: any[]): any
}
}
```
声明合并： https://www.tslang.cn/docs/handbook/declaration-merging.html
Declaration Merging： https://www.typescriptlang.org/docs/handbook/declaration-merging.html

Update core define

---

packages/webpack-plugin/lib/template-compiler/compiler.js

class或style内容有换行并且有对应wx:class或wx:style指令编译出来后的内容在微信环境下异常

fix: class或style换行问题

---

packages/api-proxy/src/common/stylus/ActionSheet.styl

ActionSheet.styl 间距错误，导致stylus解析错误
解析错误示例
```css
.__mpx_actionsheet__{
display:none;
}
.show{
display:block;
}
```
应该是
```css
.__mpx_actionsheet__{
display:none;
}
.__mpx_actionsheet__.show{
display:block;
}
```

ActionSheet.styl  间距

---

packages/core/src/convertor/wxToTenon.js
packages/core/src/platform/builtInMixins/pageStatusMixin.tenon.js
packages/core/src/platform/patch/tenon/getDefaultOptions.js
packages/core/src/platform/patch/tenon/lifecycle.js
packages/webpack-plugin/lib/platform/template/wx/index.js
packages/webpack-plugin/lib/runtime/components/tenon/tenon-view.vue
packages/webpack-plugin/lib/style-compiler/plugins/hm.js

- 修复了for-index/for-item 用法在tenon运行时无法正常渲染的问题
- 修复了空view在tenon运行时渲染报错的问题
- 对齐了tenon下page和component下 created和destroyed生命周期
- 对齐了tenon onShow onHide onBack生命周期

fix: tenon runtime error

---

docs-vuepress/api/directives.md
packages/webpack-plugin/lib/platform/template/wx/index.js

* 修复输出H5 wx:class不生效问题
* 修改文档中关于wx:class 和 wx:style 的数组使用示例

修复输出H5 wx:class不生效问题

---

packages/webpack-plugin/lib/template-compiler/compiler.js

processAliStyleClassHack添加srcMode和mode同为ali时的判断,避免引用xx.ali.mpx文件时无事件代理

processAliStyleClassHack添加srcMode和mode同为ali时的判断,避免引用xx.ali.mpx文件时无事件代理

---

packages/webpack-plugin/lib/index.js
packages/webpack-plugin/lib/loader.js
packages/webpack-plugin/lib/template-compiler/compiler.js
packages/webpack-plugin/lib/template-compiler/index.js

1. 新增checkUsingComponentsRules控制检查范围，兼容以前checkUsingComponents的配置
2. 当组件在componentPlaceholder作为占位组件时，判定为已使用
3. 合并页面未使用组件，带上path一起输出（方便定位）

优化未使用组件检查checkUsingComponents

---

packages/webpack-plugin/lib/script-setup-compiler/index.js

修复 script setup move import 时注释的场景下，end loc计算不准确问题

move import 时处理有注释情况的end loc时多加了startIndex

---

packages/core/src/observer/reactive.js
packages/core/src/observer/watch.js
packages/utils/src/base.js

```js
it.only('ref', () => {
const a = ref(0)
const b = computed(() => {
return a.value
})
a.value = -0
expect(b.value).toBe(-0)
})
```
如上述test， 期望`a.value`改为`-0`时，computed`b`的`value`也响应变化，现状未变化。

fix: reactive set相同值badcase -0 & 0

---

packages/utils/src/index.js

是否可以优化成`export * from './base'`,我发现我忘记导出了

fix: hanchange export

---

packages/webpack-plugin/lib/loader.js
packages/webpack-plugin/lib/selector.js
packages/webpack-plugin/lib/utils/get-entry-name.js
packages/webpack-plugin/lib/utils/ts-loader-watch-run-loader-filter.js

*  兼容处理处理ts-loader中watch-run/updateFile逻辑，直接跳过所有Mpx文件相关loader
*  兼容处理某个entry未被任何模块引用时，get-entry-module方法中entryModule为空的场景

Fix ts loader watch run error

---

packages/webpack-plugin/lib/runtime/optionProcessor.js

修复部分场景下：从二级页面浏览器导航返回action为undefined时，未判断前后两个页面是否为tabbar item

fix:修复tabbar输出H5无法切换的问题

---

packages/webpack-plugin/lib/style-compiler/index.js

调整用户 postcss 插件的执行顺序。
修复问题：
当用户使用 [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables) 插件且将 [preserve](https://github.com/MadLittleMods/postcss-css-variables#preserve-default-false) 设置为 true 时，会使内置插件中的 rpx 等带有注释处理功能的插件无法按预期方式执行。
通过将内置插件的执行顺序提前用以解决此问题。

fix(style-compiler): Adjusting the Postcss plugin order

---

packages/webpack-plugin/lib/index.js
packages/webpack-plugin/lib/json-compiler/helper.js
packages/webpack-plugin/lib/json-compiler/index.js
packages/webpack-plugin/lib/utils/ts-loader-watch-run-loader-filter.js
packages/webpack-plugin/lib/wxss/runtime/api.js

* 修改wxss/runtime部分高级语法为es5
* 修改异步分包判断逻辑，避免placeholder校验逻辑在非异步分包平台开启
* 修复ts-loader watch-run json parse报错问题

fix:修改部分高级语法

---

packages/core/src/platform/builtInMixins/refsMixin.web.js

When using underscores as the value of refs prop, it will be lost during web runtime

fix(web): fix refs regexp

---

packages/core/@types/index.d.ts

实现以下效果
```js
createComponent({
properties: {
data: {
type: Object as PropType<{ xxx: string }>,
value: {
xxx: 'xxx',
},
},
},
setup(props) {
props.data.xxx // 开发工具自动类型提示
return {}
},
})
```

Feat 支持PropType类型

---

packages/webpack-plugin/lib/json-compiler/default-page.mpx

局部构建兜底页面中，获取并显示当前路由。便于开发、测试跳转时查看

feat: 局部构建兜底页面增加当前页面路由显示

---

packages/core/@types/index.d.ts
packages/webpack-plugin/lib/script-setup-compiler/index.js

包含 2 更改：
[修复 mpx setup 区块内，ts类型定义会被合并为一行的问题](https://github.com/didi/mpx/pull/1352/commits/bf7cb5cfd729448d3872552ed8eb765c5cabcae7)
[perf: mpx.use 支持插件参数推导](https://github.com/didi/mpx/pull/1352/commits/140d794d2e7faa56b39f138e36e5c8dccd8b8835)

fix: 修复 mpx setup 区块内，ts类型定义会被合并为一行的问题

---

docs-vuepress/api/compile.md
packages/webpack-plugin/lib/style-compiler/index.js
packages/webpack-plugin/lib/style-compiler/load-postcss-config.js

**注意**：默认添加的 postcss 插件均会在`mpx的内置插件`（例如如rpx插件等）之后处理。如需使配置的插件优先于内置插件，可以在 `postcssInlineConfig` 中添加 `mpxPrePlugins` 配置：
```js
// vue.config.js
module.exports = defineConfig({
pluginOptions: {
mpx: {
plugin: {
postcssInlineConfig: {
plugins: [
require('postcss-import'),
require('postcss-preset-env'),
],
mpxPrePlugins: [
require('cssnano'),
require('autoprefixer')
]
// 以下写法同理
// mpxPrePlugins: {
//   'cssnano': {},
//   'autoprefixer': {}
// }
}
}
}
}
})
```
在上面这个例子当中，postcss 插件处理的最终顺序为：`cssnano` -> `autoprefixer` -> `mpx内置插件` -> `postcss-import` -> `postcss-preset-env`
**注意：在 `mpxPrePlugins` 中配置的 postcss 插件如果不通过 mpx 进行处理，那么将不会生效。**

build(style): 增加前置postcss插件能力支持

---

packages/webpack-plugin/lib/index.js

~~- 由于 pnpm nested node_modules 非扁平结构，尤其是在 peers 造成的排列组合路径时，之前的匹配逻辑会错误命中。解决方案：从之前的绝对路径改为相对路径匹配，`pnpm` 路径下截取最后出现的 `node_modules` 之后的路径，这与常规的 `npm` 路径一致。~~
仅修改特定 `@mpxjs` 匹配规则 -> `node_modules/@mpxjs`，`options.transMpxRules` 通过在项目中配置对应的路径规则来解决 `pnpm` 下的问题。

fix: pnpm下跨平台转换全局对象时路径匹配逻辑失效

---

packages/unocss-base/lib/index.js
packages/unocss-plugin/lib/index.js
packages/unocss-plugin/lib/transform.js

1.transformGroups支持选择器写法&配置分隔符
2.preflightRoot 对齐unocss，变更 'page'  ->  'page,view,text,::before,::after,::backdrop',修复父级变量影响子级的问题。我们只给 view,text加了，应该能覆盖大部分场景吧？
3. web 对齐需要 不同的preflightRoot，所以preflightRoot里还应有'div,span'， 看看我们是分环境配置，还是直接写在一起呢

Fix unocss feature cwy

---

packages/store/@types/index.d.ts

修复当在ts里使用 `export default createStore()`时的报错 "default export of the module has or is using private name 'Store'."

修复@mpxjs/store的类型问题

---

packages/unocss-base/lib/index.js

::backdrop在部分真机（iphone）下会导致渲染异常，与模拟器表现不符合。具体表现为含::backdrop的分组选择器样式失效。
``` css
/* 模拟器正常，真机失效 */
view,.abc,::backdrop {
} 
/*  模拟器、真机均正常 */
view,.abc {
}
```

fix: 小程序部分机型::backdrop异常

---

packages/webpack-plugin/lib/runtime/components/react/mpx-view.tsx

修复当background-size设置为`100% auto`时，padding-right会在盒子外，背景图宽度与盒子宽度不相等。

fix(view): fix background fill.

---

docs-vuepress/api/compile.md
docs-vuepress/guide/advance/async-subpackage.md
packages/webpack-plugin/lib/index.js

* 支持通过disableRequireAsync配置项关闭分包异步化能力

Feat support require async options

---

packages/api-proxy/src/platform/api/create-intersection-observer/rnIntersectionObserver.js
packages/core/src/platform/createApp.ios.js

1. 安卓导航条回退的时候，动画与screen动画割裂
2. 安卓导航条初始化时闪现路径问题
3. 相交api使用layout里面的x值，x值目前不对，暂时先修改为不参考x值

bugfix: 导航条在安卓上体验问题&相交api错误

---

packages/webpack-plugin/lib/template-compiler/compiler.js
packages/webpack-plugin/lib/utils/pre-process-json.js

processShowStyle 添加是否为 virtualHost 的判断

fix: processShowStyle 添加是否为 virtualHost 的判断

---

docs-vitepress/.vitepress/config.ts
docs-vitepress/.vitepress/theme/styles/index.css
docs-vitepress/api/ApiIndex.vue

vitepress 默认文档样式是靛蓝色系，和 Mpx 绿色系风格不搭（比如  <a> 标签颜色、hover颜色、搜索框颜色等等），修改成绿色系风格，和以前 vuepress 版本定制风格对齐。

docs: update styles

---

docs-vitepress/.vitepress/config.ts
docs-vitepress/.vitepress/theme/components/AlgoliaSearchBox.vue
docs-vitepress/.vitepress/theme/components/MobileView.vue
docs-vitepress/.vitepress/theme/components/Navbar.vue
docs-vitepress/.vitepress/theme/components/Swiper.vue
docs-vitepress/.vitepress/theme/global-components/Content.vue
docs-vitepress/.vitepress/theme/global-components/Footer.vue
docs-vitepress/.vitepress/theme/translations.ts
docs-vitepress/index.md
docs-vitepress/package.json
docs-vitepress/public/manifest.webmanifest
docs-vitepress/public/service-worker.js

- 尝试删除旧版本 service worker，避免访问不到新版站点
- 首页部分样式和旧版本对齐

Docs vitepress update

---

packages/fetch/src/xfetch.js

命中缓存需要copy一个新的response对象用于添加isCache标识，防止污染原本的response对象。

fix: 修复预请求isCache标识不准问题

---

packages/webpack-plugin/package.json

fix: hummer相关依赖使用宿主环境的版本

---

packages/size-report/package.json
packages/size-report/src/utils/parse-asset.js

size-report analyze
before:
```unknown
(window.webpackJsonp = window.webpackJsonp||[]).push([[<chunks>], <modules>, ...])
^^^^
```
after:
```unknown
var a = 'push';
(window.webpackJsonp = window.webpackJsonp||[])[a]([[<chunks>], <modules>, ...])
^^^
```

fix: async chunk push expression

---

packages/api-proxy/src/common/js/utils.js

* 修复api-proxy 内 getCurrentPageId 方法报错

fix: 修复getCurrentPageId 方法报错

---

packages/webpack-plugin/lib/runtime/components/react/mpx-swiper-item.tsx

- 问题现象：鸿蒙端上，swiper 组件渲染（wx:if 控制）时 item 高度没有自动跟随 step.value 变化，得等到首次自动滚动或者 touch 之后高度正常变化。

fix: delayed rendering issue of the Swiper in HarmonyOS

---

packages/webpack-plugin/lib/index.js

windows路径使用\分隔导致mpxjs中getEnvObj中的wx被替换为mpx，出现循环依赖

fix: 修复windows下替换wx为mpx runtime逻辑异常

---

packages/core/src/core/proxy.js
packages/core/src/platform/patch/getDefaultOptions.web.js

与Vue表现拉齐，选项式 Api 生命周期中依然可通过 getCurrentInstance 获取当前组件实例

fix: 修复选项式api下生命周期中getCurrentInstance为空问题

---

packages/fetch/README.md
packages/fetch/src/xfetch.js

默认开启 usePre 后，如果命中缓存则会将缓存清空，否则将会覆盖缓存。但有时我们希望本次usePre仅使用/产生缓存，此时可通过 usePre.mode 参数控制缓存的生产/消费模式
usePre.mode: 可选值 'auto','consumer','producer'， 默认为'auto'
+ auto: 存在缓存时消费缓存，不存在时生产缓存
+ consumer: 仅消费缓存，不存在缓存时发起网络请求，且不产生新的缓存
+ producer: 仅生产缓存，一定会发起网络请求并产生新的缓存
```js
// preload
mpx.xfetch.fetch({
url: 'http://xxx.com',
usePre: {
enable: true,
// 仅生产缓存，用于提前请求达到加速效果
mode: 'producer'
}
})
// use preload
mpx.xfetch.fetch({
url: 'http://xxx.com',
usePre: {
enable: true,
// 消费 preload 产生的缓存
mode: 'consumer'
}
})
```

Feat fetch usepre 支持缓存的生产/消费模式控制

---

packages/webpack-plugin/lib/runtime/components/react/mpx-keyboard-avoiding-view.tsx

- 某些特殊机型下隐藏键盘可能会先触发一次 `keyboardWillShow`，比如机型 iPhone 11 Pro，可能会导致显隐动画冲突。防止未来可能的类似冲突，增加状态标记 `isShow` + `clearTimeout` + `cancelAnimation` 来优化。

fix(rn): optimize keyboard to prevent animation conflicts
