didi/mpx

- packages/promisify/src/promisify.js
> fix promisify bug

- packages/webpack-plugin/lib/template-compiler/compiler.js
Fix reading properties from undefined ast node when the template file is empty
> Fix reading properties from undefined ast node

- packages/webpack-plugin/lib/json-compiler/index.js
- packages/webpack-plugin/lib/loader.js
- packages/webpack-plugin/lib/native-loader.js
- packages/webpack-plugin/lib/parser.js
- packages/webpack-plugin/lib/selector.js
- packages/webpack-plugin/lib/template-compiler/compiler.js
- packages/webpack-plugin/lib/utils/mpx-json.js
Add `__dirname` and `__filename` and relative path requiring
> feature: full commonjs implementation for dynamic json

- packages/core/src/convertor/wxToAli.js
- packages/core/src/core/createStore.js
- packages/core/src/core/mapStore.js
- packages/core/src/core/mergeOptions.js
- packages/core/src/core/proxy.js
- packages/core/src/core/transferOptions.js
- packages/core/src/platform/builtInMixins/proxyEventMixin.js
- packages/webpack-plugin/lib/loader.js
- packages/webpack-plugin/lib/native-loader.js
- packages/webpack-plugin/lib/template-compiler/compiler.js
> remove currentResource inject in production mode and ignore no need console.error in production mode

- packages/webpack-plugin/lib/json-compiler/index.js
- packages/webpack-plugin/lib/utils/mpx-json.js
> fix: mpx json resolve error in watch mode

- packages/core/src/platform/builtInMixins/proxyEventMixin.js
- packages/webpack-plugin/lib/platform/template/wx/component-config/button.js
- packages/webpack-plugin/lib/platform/template/wx/index.js
- packages/webpack-plugin/test/platform/wx/template.spec.js
> update event bind trans rules for tt and make dynamic value in open-type be a warning replace error

- packages/webpack-plugin/lib/platform/template/wx/index.js
> feat: 更新百度小程序支持事件列表

- packages/fetch/src/request.js
> fix: 修复fetch data没有过滤空值

- packages/webpack-plugin/lib/platform/json/wx/index.js
tt add  `navigateToMiniProgramAppIdList|permission`  rule
> fix: 头条增加navigateToMiniProgramAppIdList|permission规则

- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/native-loader.js
> feat: nativeOptions.cssLangs

- docs-vuepress/api/directives.md
> Doc rebuild

- docs-vuepress/api/compile.md
> docs:更新mode,navtiveOptions等文档

- packages/core/src/platform/builtInMixins/pageTitleMixin.js
- packages/webpack-plugin/lib/loader.js
- packages/webpack-plugin/lib/runtime/optionProcessor.js
- packages/webpack-plugin/lib/web/processScript.js
> Feat adapt web json

- packages/webpack-plugin/lib/json-compiler/index.js
- packages/webpack-plugin/lib/platform/template/wx/component-config/form.js
Fix:
1. wrong accumulated context for subPackages
1. now bytedance supports reporting form ID
> [WIP] Fix a Few Compiler's Bugs

- packages/webpack-plugin/lib/platform/json/wx/index.js
(cherry picked from commit ef35db99e2740885e1463236705ea17d26839797)
> update json trans rules for fix #506

- packages/core/src/platform/patch/wx/getDefaultOptions.js
> fix: 修复数据错误

- packages/core/src/platform/builtInMixins/pageScrollMixin.js
与微信小程序对齐，disableScroll 为 true 时，页面只能上拉，不能向下滚动。
> fix page scroll

- packages/core/src/platform/builtInMixins/pageScrollMixin.js
- packages/webpack-plugin/lib/runtime/reset.css
适配web的backgroundColor和backgroundTextStyle配置
> feat: adapt to web loading style

- packages/webpack-plugin/lib/runtime/components/web/mpx-button.vue
> fix: 格式化导致的样式问题

- docs-vuepress/guide/basic/start.md
> docs: update npm script

- packages/webpack-plugin/lib/runtime/components/web/mpx-image.vue
added styles:
```js
style.backgroundPosition = 'center'
style.backgroundRepeat = 'no-repeat'
```
> fix: solve problems when image's mode = aspectFit

- packages/api-proxy/src/web/api/index.js
- packages/api-proxy/src/web/api/page-scroll-to/index.js
- packages/core/src/platform/builtInMixins/pageScrollMixin.js
> feat: pageScrollTo in web

- packages/webpack-plugin/lib/runtime/components/web/mpx-button.vue
> update: 读取配置兼容小程序v1/v2样式

- docs-vuepress/guide/advance/dll-plugin.md
> 添加使用 DllPlugin 插件文档

- docs-vuepress/api/builtIn.md
> update: supplementary documentation

- docs-vuepress/guide/advance/size-report.md
> 补充 sizeReport 文档

- packages/api-proxy/src/common/js/utils.js
- packages/api-proxy/src/mini/platform/wxToQq.js
- packages/api-proxy/src/mini/transform.js
wxToQqApi 添加 requestSubscribeMessage 转换
> wxToQqApi 添加 requestSubscribeMessage 转换

- docs-vuepress/guide/advance/image-process.md
图像文档-增加outputPathCDN，publicPathScope相关说明
> image add outputPathCDN

- packages/api-proxy/src/web/api/toast/Toast.js
fix the bug cause by Browser compatibility
> fix(api-proxy/showloading): replace replaceWith with replaceChild

- packages/api-proxy/src/qa/router/index.js
- packages/core/src/core/proxy.js
- packages/core/src/platform/builtInMixins/proxyEventMixin.js
- packages/core/src/platform/builtInMixins/refsMixin.qa.js
- packages/webpack-plugin/lib/qaHelper/genTabBar.js
- packages/webpack-plugin/lib/qaHelper/tabBar.ux
- packages/webpack-plugin/lib/template-compiler/compiler.js
快应用tabbar：
嗯，按照自己的思路搞完了，但是有两个不完美的地方。
1. 配置tabbar的时候，iconpath, 如果直接走生成ux文件的方式，因为没编译找不到路径，目前用的是链接
2. switchTab 用的triggerEvent的方式实现的，没办法通过统一的mpx.switchTab
> Feat lyfqa tab bar

- packages/webpack-plugin/lib/wxss/getImportPrefix.js
解决 issue：
https://github.com/didi/mpx/issues/699
https://github.com/didi/mpx/issues/697
> fix the path compatibility between windows and linux

- docs-vuepress/guide/extend/api-proxy.md
> docs: 修改 api-proxy 单独使用示例

- docs-vuepress/guide/advance/npm.md
> 使用npm包文档中 添加page object配置说明

- docs-vuepress/api/compile.md
补充subpackageModulesRules配置项使用方式
> 补充subpackageModulesRules配置项使用方式

- packages/webpack-plugin/lib/runtime/optionProcessor.js
- packages/webpack-plugin/lib/web/processTemplate.js
> 输出H5处理 multi root element 情况

- packages/webpack-plugin/lib/runtime/components/web/getInnerListeners.js
> bugfix:修复输出H5时tap事件失效问题

- packages/api-proxy/package-lock.json
- packages/api-proxy/package.json
> 升级api-proxy中axios版本

- packages/core/@types/index.d.ts
> fix(core/types): fix  $refs types

- packages/fetch/src/request.js
- packages/fetch/src/xfetch.js
修复 用户未传入 useQuene 配置时调用 `addLowPriorityWhiteList` 报错的问题
添加 tt 小程序 adapter
> Fix fetch error

- packages/webpack-plugin/lib/built-in-loader.js
- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/json-compiler/index.js
- packages/webpack-plugin/lib/loader.js
- packages/webpack-plugin/lib/parser.js
- packages/webpack-plugin/lib/resolver/AddEnvPlugin.js
- packages/webpack-plugin/lib/selector.js
- packages/webpack-plugin/lib/template-compiler/compiler.js
- packages/webpack-plugin/lib/template-compiler/index.js
- packages/webpack-plugin/lib/web/processJSON.js
- packages/webpack-plugin/test/platform/common/mode.spec.js
- packages/webpack-plugin/test/platform/util.js
> Feat env condition compilation

- docs-vuepress/guide/basic/list-render.md
> docs: 添加列表渲染特殊处理方式

- docs-vuepress/guide/basic/two-way-binding.md
- packages/webpack-plugin/lib/platform/template/wx/index.js
- packages/webpack-plugin/lib/template-compiler/compiler.js
- packages/webpack-plugin/lib/utils/is-url-request.js
- packages/webpack-plugin/lib/utils/string.js
> Fixbug compiler reg

- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/json-compiler/index.js
- packages/webpack-plugin/lib/plugin-loader.js
插件开发支持 GenericsImplementation 的配置处理
> 插件支持 GenericsImplementation 的配置处理

- packages/webpack-plugin/lib/index.js
Fix debounce runtime 无 Date 问题
> Fix debounce runtime 无 Date 问题

- packages/core/src/platform/patch/index.js
- packages/webpack-plugin/lib/loader.js
> 添加 ctor 和 resourcetype 的判断校验

- packages/webpack-plugin/lib/helpers.js
- packages/webpack-plugin/lib/loader.js
- packages/webpack-plugin/lib/staticConfig.js
- packages/webpack-plugin/lib/style-compiler/index.js
- packages/webpack-plugin/lib/template-compiler/compiler.js
1、将mpx-app-scope、mpx-root-view提取为静态配置项
2、mpx-root-view节点解耦跑流程
3、page、component判断优化，去除helper中判断参数了
4、mpxShow优化
> 平台差异抹平逻辑优化

- packages/webpack-plugin/lib/runtime/components/web/getInnerListeners.js
修复上下两层div重叠时多触发一次下方div click 事件的问题，添加isTouchDevice 检测
> 修复上下两层div重叠时多触发一次下方div click 事件的问题，添加isTouchDevice 检测

- packages/api-proxy/package.json
- packages/core/package.json
> add package.json main field

- packages/webpack-plugin/lib/platform/json/wx/index.js
- packages/webpack-plugin/lib/platform/template/wx/component-config/navigator.js
- packages/webpack-plugin/lib/runtime/stringify.wxs
修复部分ali平台已经支持的属性的过滤，比如去除app.json配置中对backgroundColor的过滤
> 去除app.json配置中对backgroundColor的过滤

- .github/workflows/docs.yml
- docs-vuepress/.vuepress/theme/layouts/GlobalLayout.vue
- docs-vuepress/desc.md
fix document not defined (computed isMobile)
> fix: isMobile computed

- .github/workflows/docs.yml
> fix: docs.yml中还原 env.GIT_DIFF 配置

- packages/webpack-plugin/lib/runtime/components/web/mpx-textarea.vue
> fix: domProps maxLength传参问题

- .github/workflows/docs.yml
- packages/webpack-plugin/lib/wxs/wxs-pre-loader.js
> 修复支付宝环境arguments replace问题

- docs-vuepress/guide/advance/subpackage.md
> 添加独立分包初始化逻辑说明文档

- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/json-compiler/helper.js
> fix page path with \/

- packages/core/@types/global.d.ts
add vue-i18n mergeMessage ts declaration
> add vue-i18n mergeMessage ts declaration

- packages/core/@types/global.d.ts
- packages/core/@types/index.d.ts
- packages/webpack-plugin/lib/style-compiler/plugins/scope-id.js
- packages/webpack-plugin/lib/style-compiler/plugins/trans-special.js
- packages/webpack-plugin/package.json
修复@mpxjs/core global.d.ts中存在import语法导致全局特性失效的问题
> 修复因global.d.ts中存在import语法导致全局特性失效的问题

- packages/webpack-plugin/lib/extractor.js
- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/loader.js
- packages/webpack-plugin/lib/wxml/loader.js
- packages/webpack-plugin/lib/wxss/loader.js
修复app 中 使用 style 标签src 引入css 无filename 问题
> 修复app 中 使用 style 标签src 引入css 无filename 问题

- packages/webpack-plugin/lib/dependencies/DynamicEntryDependency.js
- packages/webpack-plugin/lib/json-compiler/index.js
> fix(webpack-plugin): add custom-tab-bar component into output

- packages/webpack-plugin/lib/template-compiler/compiler.js
> 修改 ali root view 节点问题

- packages/webpack-plugin/lib/template-compiler/compiler.js
* 修复支付宝小程序使用自定义组件slot功能时异常问题
* 修复支付宝小程序属性匹配问题
> Fixbug ali root view slot

- packages/webpack-plugin/lib/loader.js
> 修改app style src 引入问题

- packages/webpack-plugin/lib/template-compiler/compiler.js
- test/e2e/plugin-project/test/components/list.spec.js
> 修复 root view processShow 问题

- docs-vuepress/api/extend.md
- docs-vuepress/guide/advance/progressive.md
- docs-vuepress/guide/advance/size-report.md
- docs-vuepress/guide/advance/subpackage.md
- docs-vuepress/guide/basic/refs.md
- packages/webpack-plugin/lib/index.js
- test/e2e/plugin-project/test/components/list.spec.js
> Feat add some feat doc

- docs-vuepress/.vuepress/theme/components/AlgoliaSearchBox.vue
- package.json
fix(algolia):fix online search failed without appId
> Fix algolia search

- packages/webpack-plugin/lib/web/processJSON.js
- packages/webpack-plugin/lib/web/processScript.js
> 输出H5支持自定义async chunk name

- packages/fetch/@types/index.d.ts
> 补充fetch相关类型声明

- packages/webpack-plugin/lib/json-compiler/helper.js
json-compiler 中的processComponent添加环境区分
> json-compiler 中的processComponent添加环境区分

- packages/fetch/src/interceptorManager.js
> 修改fetch拦截器

- docs-vuepress/api/compile.md
> Update outdated content in `postcssInlineConfig`

- docs-vuepress/.vuepress/config.js
- docs-vuepress/articles/2.7-release.md
- docs-vuepress/guide/advance/async-subpackage.md
- docs-vuepress/guide/advance/subpackage.md
> 修改分包相关文档结构

- docs-vuepress/.vuepress/theme/components/CodeList.vue
- docs-vuepress/.vuepress/theme/global-components/Content.vue
- docs-vuepress/README.md
> Fix docs some error

- packages/webpack-plugin/lib/index.js
> 修复异步jsmodule判断问题

- packages/webpack-plugin/lib/index.js
> 修复支付宝平台构建独立组件或页面js不执行问题

- packages/webpack-plugin/lib/index.js
修复支付宝环境regenerator-runtime Function replace问题
> 修复支付宝环境regenerator-runtime Function replace问题

- packages/api-proxy/src/mini/promisify.js
> reportEvent 添加非primiseify白名单

- packages/webpack-plugin/lib/helpers.js
- packages/webpack-plugin/lib/selector.js
> feat: 支持 thread-loader

- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/wxs/WxsPlugin.js
修复javascript parser hooks钩子注册问题
> 修复javascript parser hooks钩子注册问题

- packages/webpack-plugin/lib/loader.js
> 修改entryName生成问题

- packages/webpack-plugin/lib/index.js
修复styleLoader 顺序导致的postcss报错问题
> 修复styleLoader 顺序导致的postcss报错问题

- packages/webpack-plugin/lib/web/processJSON.js
修改输出H5 processComponent 组件地址错误时的报错处理
> 修改输出H5 processComponent 组件地址错误时的报错处理

- packages/core/src/convertor/wxToTt.js
- packages/webpack-plugin/lib/resolver/FixDescriptionInfoPlugin.js
* 修复输出头条小程序内建behavior判断问题
* 修复局部编译resolver plugin 路径获取报错问题
> Fixbug tt behavior

- packages/core/src/convertor/wxToTt.js
- packages/webpack-plugin/lib/resolver/FixDescriptionInfoPlugin.js
- packages/webpack-plugin/lib/web/processJSON.js
* 修复输出头条内建behavior转换判断问题
* 修复输出H5 processJson 组件路径not found 报错优化问题
* 修复局部构建 resourcepath 为 false 时路径解析报错问题
> Fixbug tt behavior master

- docs-vuepress/guide/basic/css.md
- packages/webpack-plugin/lib/json-compiler/index.js
- packages/webpack-plugin/lib/wxss/loader.js
- packages/webpack-plugin/lib/wxss/options.json
修复wxss loader 无css压缩功能，添加cssnano 压缩 css 功能
> 修复wxss loader 无css压缩功能，添加cssnano 压缩 css 功能

- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/utils/check-core-version-match.js
添加@mpxjs/webpack-plugin 和 @mpxjs/core 版本检查功能
> feat:添加@mpxjs/core 版本检查功能

- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/utils/check-core-version-match.js
添加@mpxjs/webpack-plugin 和 @mpxjs/core 版本匹配检查功能
> feat: 添加@mpxjs/webpack-plugin 和 @mpxjs/core 版本匹配检查功能

- docs-vuepress/guide/basic/css.md
- packages/utils/src/object.js
- packages/webpack-plugin/lib/json-compiler/index.js
- packages/webpack-plugin/lib/wxss/loader.js
- packages/webpack-plugin/lib/wxss/options.json
> css添加cssnano压缩处理

- docs-vuepress/guide/migrate/2.8.md
remove extra character `s` in [https://mpxjs.cn/guide/migrate/2.8.html#%E4%BE%9D%E8%B5%96%E5%8D%87%E7%BA%A7](https://mpxjs.cn/guide/migrate/2.8.html#%E4%BE%9D%E8%B5%96%E5%8D%87%E7%BA%A7)
> doc: remove extra character

- docs-vuepress/guide/composition-api/composition-api.md
- packages/core/@types/index.d.ts
> Fix ts type error

- packages/core/src/core/mergeOptions.js
> 修复getMixin报错

- packages/webpack-plugin/lib/wxss/plugins/postcss-url-parser.js
2.7版本修复style中的url图片没有被转换为base64的问题
> fix:2.7版本修复style中的url图片没有被转换为base64的问题

- packages/core/@types/index.d.ts
- packages/webpack-plugin/lib/script-setup-compiler/index.js
修复script setup中properties defatulString拼接和defineProps类型定义问题
> 修复script setup中properties defatulString拼接和defineProps类型定义问题

- packages/webpack-plugin/lib/json-compiler/index.js
修复问题：app.mpx 的 json 配置当中声明了 worker 的代码，编译流程报错。
> [Fix]worker js build error

- packages/core/src/core/innerLifecycle.js
- packages/core/src/core/proxy.js
- packages/core/src/index.js
> 2.7版本添加内置生命周期导出兼容2.8版本写法

- packages/webpack-plugin/lib/wxss/loader.js
fix:修复wxss/runtime/api经过babel报错问题
> fix:修复wxss/runtime/api经过babel报错问题

- packages/webpack-plugin/lib/wxss/loader.js
fix:修复runtime/api经过babel导致报错问题
> fix:修复runtime/api经过babel导致报错问题

- packages/core/src/platform/export/index.web.js
> fix web effectScope

- README.md
- docs-vuepress/.vuepress/theme/components/Popover.vue
- docs-vuepress/README.md
- packages/webpack-plugin/lib/loader.js
> fix:避免多次创建appEntry

- packages/webpack-plugin/lib/runtime/i18n.wxs
添加i18n interpolate 方法中的values判空直接返回message逻辑
> fix:添加i18n interpolate 方法中的values判空直接反馈message逻辑

- packages/core/@types/index.d.ts
> fix: add type markRaw

- docs-vuepress/guide/advance/async-subpackage.md
> 修改关于跨分包 JS 代码引用部分的文档

- packages/webpack-plugin/lib/parser.js
- packages/windicss-plugin/lib/index.js
- packages/windicss-plugin/lib/loader/windicss-app.js
- packages/windicss-plugin/package.json
> windicss输出web

- packages/webpack-plugin/lib/platform/template/wx/component-config/button.js
- packages/webpack-plugin/lib/runtime/components/web/getInnerListeners.js
* 补充头条小程序button按钮open-type属性支持范围
* 修复ssr场景document报错
> Fix some error

- packages/webpack-plugin/lib/wxss/runtime/api.js
- packages/webpack-plugin/lib/wxss/runtime/noSourceMaps.js
- packages/webpack-plugin/lib/wxss/runtime/sourceMaps.js
> fix:修复wxss中的高级语法问题

- .github/workflows/test.yml
> fix:修复fork仓库pr无法触发test action的问题

- packages/size-report/src/SizeReportPlugin.js
> feat: size-report添加预警阈值功能

- packages/webpack-plugin/lib/wxss/runtime/api.js
- packages/webpack-plugin/lib/wxss/runtime/sourceMaps.js
> feat:save change

- packages/webpack-plugin/lib/template-compiler/compiler.js
> feat(hummer): hummer mode support AtMode

- packages/core/src/platform/export/index.tenon.js
> fix: tenon runtime set&del error

- packages/size-report/README.md
- packages/size-report/src/SizeReportPlugin.js
size-report 插件阈值校验时支持忽略部分分包体积功能
> Feat size report support ignore

- docs-vuepress/.vuepress/config.js
> fix:修复文档prefetch

- packages/core/src/vuePlugin.js
- packages/webpack-plugin/lib/platform/template/wx/index.js
> Fix web compile

- packages/core/src/platform/patch/tenon/getDefaultOptions.js
修改setup中initproxy时错误执行CREATED生命周期的问题
> Feat hummer mode

- packages/unocss-base/lib/index.js
打开preflight,替换*,::before,::after为page，则可以获取到全局变量
> fix: 修复部分功能需要全局变量未定义问题

- docs-vuepress/api/compile.md
- packages/webpack-plugin/lib/template-compiler/compiler.js
修复输出 ali/web root-view srcMode判断问题
> fix: 修复输出ali/web root-view srcMode判断问题

- packages/webpack-plugin/lib/style-compiler/index.js
> 输出web mpx-root-view添加class样式

- packages/api-proxy/src/web/api/request/index.js
修复输出web request api 中 datatype=text时返回值为json问题
> fix: 修复输出web，mpx.request datatype=text时返回值为json问题

- docs-vuepress/api/compile.md
- packages/core/src/platform/builtInMixins/proxyEventMixin.js
- packages/core/src/platform/builtInMixins/proxyEventMixin.web.js
- packages/core/src/vuePlugin.js
- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/template-compiler/compiler.js
- packages/webpack-plugin/lib/template-compiler/index.js
- packages/webpack-plugin/lib/web/processTemplate.js
* root-view 方案改动，输出支付宝外层包裹，输出web 内层包裹走v-on="$listener"
> Feat root view revision 10.31

- packages/webpack-plugin/package.json
修改mpxjs/webpack-plugin peer webpack版本
> fix: 修改mpxjs/webpack-plugin peer webpack版本

- packages/webpack-plugin/lib/dependencies/ResolveDependency.js
优化resolve处理逻辑,移除原来的正则匹配，新增scheme匹配
> feat(tenon): 优化resolve处理逻辑

- packages/core/package.json
- packages/webpack-plugin/lib/dependencies/ResolveDependency.js
feat(tenon): 更新tenon-store依赖版本优化customkey处理逻辑
feat(tenon): 优化reslove逻辑
> feat(tenon): 优化reslove逻辑

- packages/webpack-plugin/lib/json-compiler/index.js
* 修复跨端输出支付宝时，asyncPakcageRules中配置的view没有转为mpx-view问题
> Fix ali placeholder view

- README.md
- packages/webpack-plugin/lib/index.js
> feat: 修复配置splitChunks为false时的判断情况

- docs/.gitignore
> fix: delete gitignore

- package.json
> fix: 删除项目types/webpack依赖

- docs-vuepress/api/compile.md
- docs-vuepress/guide/advance/platform.md
* 修改api/compile中的externalClass配置描述
* 修改跨平台输出mode部分描述
> Feat mode change docs

- packages/webpack-plugin/lib/utils/ts-loader-watch-run-loader-filter.js
修复windows环境下tsWatchFilterLoader方法路径判断问题
> fix: 修复windows环境下tsWatchFilterLoader方法路径判断问题

- packages/core/README.md
> docs: 调整修改mpxjs/core readme

- packages/size-report/src/SizeReportPlugin.js
修复 size-report 统计 concatenatedModule 体积问题
> fix: 修复 size-report 统计 concatenatedModule 体积问题

- packages/webpack-plugin/lib/runtime/components/tenon/getInnerListeners.js
- packages/webpack-plugin/lib/runtime/components/tenon/tenon-input.vue
- packages/webpack-plugin/lib/runtime/components/tenon/tenon-textarea.vue
1、修复textarea组件wx:model
2、修复input样式问题 & 事件触发
> fix: 修复input组件和textarea组件运行时错误

- packages/webpack-plugin/lib/platform/template/wx/component-config/input.js
> fix: 修复输出tt小程序input type 类型支持问题

- packages/webpack-plugin/lib/template-compiler/trans-dynamic-class-expr.js
> Feat wxclass escape

- packages/webpack-plugin/lib/style-compiler/index.js
> Fix app line height

- packages/webpack-plugin/lib/template-compiler/compiler.js
> fix: component range 属性支持空格

- packages/webpack-plugin/lib/dependencies/ResolveDependency.js
- packages/webpack-plugin/lib/helpers.js
- packages/webpack-plugin/lib/index.js
> fix: getRequire 方法参数添加默认值

- packages/webpack-plugin/lib/runtime/components/tenon/tenon-input.vue
修复hummer侧，tenon-input在初始化时value有值的情况下不生效的问题
> bugFix: 修复tenon-input初始化value不生效

- packages/webpack-plugin/lib/resolver/PackageEntryPlugin.js
修复 packageEntryPlugin 循环 resolve 问题
> fix: resolve plugin packageEntryPlugin 循环resolve问题

- docs-vuepress/rn-component.md
- packages/core/src/convertor/wxToReact.js
- packages/core/src/platform/patch/react/getDefaultOptions.ios.js
> docs: 补充输出RN自定义组件相关参数、属性、实例方法支持文档

- packages/webpack-plugin/lib/web/processTemplate.js
> fix: 修复输出H5 env attr 不生效问题

- packages/webpack-plugin/lib/react/processTemplate.js
> fix: 修复react env attr

- packages/webpack-plugin/lib/loader.js
- packages/webpack-plugin/lib/native-loader.js
fix: 修复queryObj ctorType undefined 问题
> feat: add ctorType

- packages/webpack-plugin/lib/template-compiler/compiler.js
range 处理后置在 postProcessComponentIs 中，规避当前无range component 不可用问题
> feat: range 处理后置在 postProcessComponentIs 中

- packages/webpack-plugin/lib/runtime/components/tenon/tenon-scroll-view.vue
> fix:修复tenon scroll-y不生效问题

- packages/webpack-plugin/lib/dependencies/DynamicEntryDependency.js
- packages/webpack-plugin/lib/template-compiler/compiler.js
* 修复resolve报错信息展示问题
* 修复编译?.导致报错问题
> Fix resolve error

- packages/size-report/src/SizeReportPlugin.js
> fix: 修复moduleEntries存储不对问题

- packages/core/src/platform/builtInMixins/proxyEventMixin.js
> fix: to thanos event data error

- packages/core/src/platform/patch/react/getDefaultOptions.ios.js
> feat: 支持getPageId方法

- packages/fetch/src/request.js
- packages/fetch/src/xfetch.js
* 修复mpx-fetch cancelToken问题
* 增加isCancel方法
> feat: 修复mpx-fetch cancelToken问题 & 增加isCancel方法

- packages/api-proxy/src/platform/api/request/index.web.js
request web 增加axios stack 与其他返回数据透出
> feat: request web 增加axios stack 与其他返回数据透出

- packages/api-proxy/src/platform/api/request/index.web.js
api-proxy 添加axios request config 全量透入处理
> feat: api-proxy 添加request config 处理

- packages/api-proxy/src/tenon/api/route/index.js
> fix:修复hummer navigateTo错误回调

- packages/webpack-plugin/lib/platform/style/wx/index.js
color var(--c)  合法
background-color: var()  不合法
border-bottom-color var(c, #fff) 不合法
border-top-color var(--c, #fff) 合法
> update:值校验支持css variable & border-radius 百分比单值展开

- packages/fetch/package.json
> feat: 添加fetch对于utils的依赖

- packages/webpack-plugin/lib/runtime/components/react/mpx-view.tsx
> fix(view): unable to display background image.

- packages/fetch/@types/index.d.ts
- packages/fetch/README.md
- packages/fetch/src/util.js
- packages/fetch/src/xfetch.js
> feat: 同步最新版本预请求至外源版本

- packages/webpack-plugin/lib/runtime/components/web/mpx-scroll-view.vue
1. 修复 scroll-view 父节点设置 scale，scroll-view 滚动异常
2. 监听 scroll-view 容器尺寸变化，动态更新滚动距离
> fix: scroll-view initLayerComputed 

- packages/webpack-plugin/lib/config.js
- packages/webpack-plugin/lib/platform/template/wx/index.js
修复输出tt/jd/dd/qq等平台时绑定事件带 "-" 时triggerEvent失效问题
> feat: 修复输出tt/jd/dd/qq等平台时bind:some-click之类绑定事件带-时triggerevent失效问题

- docs-vuepress/api/compile.md
- docs-vuepress/api/extend.md
- docs-vuepress/articles/unit-test.md
- docs-vuepress/guide/advance/size-report.md
- docs-vuepress/guide/basic/intro.md
- package.json
> Feat docs additional

- packages/webpack-plugin/lib/runtime/components/react/useAnimationHooks.ts
> fix animation api

- packages/webpack-plugin/lib/index.js
> fix: 修复输出H5 Vue 文件中样式隔离失效问题

- .eslintrc.js
- packages/core/@types/global.d.ts
- packages/core/src/platform/patch/ali/getDefaultOptions.js
- packages/core/src/runtime/createFactory.js
fix [issues](https://github.com/didi/mpx/issues/1698)
> Feat ali mixin

- packages/utils/package.json
- packages/webpack-plugin/lib/resolver/AddModePlugin.js
删除mpxjs/utils package.json内的type=module
> fix: 删除mpxjs/utils package.json内的type=module

- packages/unocss-plugin/lib/index.js
close https://github.com/didi/mpx/issues/1703
> fix: unocss support with dot path

- docs-vuepress/guide/advance/custom-output-path.md
- packages/webpack-plugin/lib/index.js
- test/e2e/miniprogram-project/config/mpxPlugin.conf.js
- test/e2e/miniprogram-wxss-loader/config/mpxPlugin.conf.js
close https://github.com/didi/mpx/issues/1582
> feat: customOutputPath 返回 resourcePath 参数

- packages/webpack-plugin/lib/template-compiler/compiler.js
> Feat change react bind event

- packages/webpack-plugin/lib/template-compiler/compiler.js
* 组件根节点添加show style添加是否为虚拟节点判断
> fix: 组件根节点添加show style添加是否为虚拟节点判断

- packages/utils/src/errorHandling.js
callWithErrorHandling 中去除 isPromise res 的判断
> feat: callWithErrorHandling 中去除 isPromise res 的判断

- docs-vitepress/guide/platform/rn.md
- 线上测试 vitepress service worker 自动更新功能
> test: docs service worker

- packages/core/src/platform/builtInMixins/refsMixin.ios.js
- packages/core/src/platform/patch/getDefaultOptions.ios.js
- packages/webpack-plugin/lib/template-compiler/compiler.js
> [optimize]ref unmount

- packages/core/src/platform/patch/getDefaultOptions.ios.js
- packages/webpack-plugin/lib/runtime/components/react/context.ts
- packages/webpack-plugin/lib/runtime/components/react/getInnerListeners.ts
- packages/webpack-plugin/lib/runtime/components/react/mpx-button.tsx
- packages/webpack-plugin/lib/runtime/components/react/mpx-movable-view.tsx
- packages/webpack-plugin/lib/runtime/components/react/mpx-portal/index.tsx
- packages/webpack-plugin/lib/runtime/components/react/mpx-portal/portal-host.tsx
- packages/webpack-plugin/lib/runtime/components/react/mpx-web-view.tsx
- packages/webpack-plugin/lib/runtime/components/react/utils.tsx
* 输出RN组件内解耦 react-native/navigation 依赖
> feat: 修改useNavigation获取逻辑

- docs-vitepress/public/service-worker.js
- 清除旧版本站点用户残留的 service-worker.js
> Docs: clear previous service-worker

- .github/workflows/docs.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- docs-vitepress/guide/platform/rn.md
> Docs rn start

- docs-vitepress/.vitepress/config.ts
- docs-vitepress/guide/advance/utility-first-css.md
- docs-vitepress/guide/platform/rn.md
- 增加 VSCode unocss 插件支持 Mpx 配置说明
- @mpxjs/cli 脚手架支持自动修改 VSCode unocss 插件配置(https://github.com/mpx-ecology/mpx-cli/pull/102)
- https://github.com/didi/mpx/issues/1898#issuecomment-2728539257
> Docs: VSCode 支持 Mpx 原子类

- packages/core/src/core/mergeOptions.js
- provide/inject 支持 mixins 选项混入
> Feat: support provide/inject mixins

- packages/webpack-plugin/lib/utils/match-condition.js
修复match condition 在windows路径适配问题
> fix: 修复match condition 在windows路径适配问题

- packages/core/src/platform/createApp.ios.js
之前onResize仅考虑屏幕方向(横屏/竖屏)变化场景，未考虑折叠屏(折叠/展开)场景。
> fix: 修复折叠屏幕不触发onResize

- docs-vitepress/.vitepress/config.ts
- docs-vitepress/api/index.md
- docs-vitepress/desc.md
- docs-vitepress/index.md
- docs-vitepress/package.json
- 升级插件版本，修复 llms.txt 乱码
- 完善 llms.txt 元数据
> Docs: 修复 llms.txt 乱码 & 完善 llms.txt 元数据

- packages/core/src/platform/patch/getDefaultOptions.ios.js
* 修复 type page wrapper return null 问题
> fix: page wrapper return

- packages/webpack-plugin/lib/runtime/components/react/mpx-picker-view-column/index.tsx
- https://github.com/didi/mpx/pull/1991
> fix: compatibility bug on Harmony

- packages/core/package.json
- packages/pinia/package.json
- packages/size-report/package.json
- packages/store/package.json
- packages/unocss-plugin/package.json
- packages/utils/package.json
- fix peer deps with beta version
> fix: 2.10.4 beta branch ci

- packages/webpack-plugin/lib/runtime/components/react/mpx-rich-text/index.tsx
问题描述：修复rn的rich-text组件背景为白色，修改为透明
> feat(*): fix backgroud color

- packages/webpack-plugin/lib/runtime/components/react/mpx-swiper-item.tsx
- RN swiper 鸿蒙端的修复改动已在 `beta` 分支验证完成，现在合并到 `master` 分支。
- https://github.com/didi/mpx/pull/2039
> fix: delayed rendering issue of the Swiper in HarmonyOS

- packages/core/@types/index.d.ts
- packages/core/src/index.js
- packages/core/src/platform/env/nav.js
- packages/core/tsconfig.json
1. 通过 stack top config 支持首个页面是否展示回退按钮、监听回退按钮的点击
2. core 中用到的 Mpx 附加类型，细化 rnConfig 的类型
> feat: 支持通过 stack top config 控制回退按钮的展示

- packages/webpack-plugin/lib/index.js
- packages/webpack-plugin/lib/react/processJSON.js
- packages/webpack-plugin/lib/utils/trans-async-sub-rules.js
> feat: 输出RN支持分包名转换

- packages/core/@types/index.d.ts
- packages/core/src/platform/env/nav.js
> feat: 简化 stack top back 配置

- packages/webpack-plugin/lib/runtime/components/react/context.ts
- packages/webpack-plugin/lib/runtime/components/react/mpx-input.tsx
- packages/webpack-plugin/lib/runtime/components/react/mpx-keyboard-avoiding-view.tsx
- 修复 RN 端 input、keyboard 组件相关问题
> fix(rn): mpx keyboard and input (2.10.6)

- packages/webpack-plugin/lib/react/processScript.js
- packages/webpack-plugin/lib/web/processMainScript.js
- packages/webpack-plugin/lib/web/processScript.js
- packages/webpack-plugin/lib/web/script-helper.js
将buildI18n由processMainScript转移至processScript，以支持在RN和web上输出单组件时支持i18n
> feat: 输出RN&Web单组件支持i18n

- packages/core/src/platform/createApp.ios.js
- packages/webpack-plugin/lib/platform/template/wx/component-config/index.js
- packages/webpack-plugin/lib/platform/template/wx/component-config/nav-container.js
- packages/webpack-plugin/lib/runtime/components/ali/mpx-nav-container.mpx
- packages/webpack-plugin/lib/runtime/components/react/context.ts
- packages/webpack-plugin/lib/runtime/components/react/mpx-input.tsx
- packages/webpack-plugin/lib/runtime/components/react/mpx-keyboard-avoiding-view.tsx
- packages/webpack-plugin/lib/runtime/components/react/mpx-nav-container.tsx
- packages/webpack-plugin/lib/runtime/components/react/nav.tsx
- packages/webpack-plugin/lib/runtime/components/react/useNavShared.ts
- packages/webpack-plugin/lib/runtime/components/web/mpx-nav-container.vue
- packages/webpack-plugin/lib/runtime/components/wx/mpx-nav-container.mpx
- packages/webpack-plugin/lib/utils/dom-tag-config.js
1. 增加 nav-container 用于 adjust-position true + 自定义 nav 场景
2. android 场景 adjust-position 行为与 ios 拉齐（需要 android 协同配置软键盘配置）
> feat: nav 与 keyboard 协作

- docs-vitepress/guide/platform/rn.md
- packages/webpack-plugin/lib/runtime/components/react/mpx-movable-view.tsx
- 添加 damping 和 friction 属性支持
- 改进超出边界后的阻尼回弹效果
- 衰减效果会随着超出距离的增加而逐渐增强阻力
---
- 修改前
https://github.com/user-attachments/assets/8c328b70-a55e-48a1-be2a-008080ff347e
- 修改后
https://github.com/user-attachments/assets/150d56ea-1527-4f84-9883-779d8a4821b8
- 微信小程序
https://github.com/user-attachments/assets/daa2bed8-dc1e-409a-8a8a-1b84ea61371c
> feat: 改进 rn 模式下的 movable-view 组件动画行为，添加 damping 和 friction 属性，惯性滑动行为对齐微信小程序

- packages/core/@types/index.d.ts
- packages/core/src/platform/createApp.ios.js
- packages/webpack-plugin/lib/runtime/components/react/context.ts
- packages/webpack-plugin/lib/runtime/components/react/mpx-input.tsx
- packages/webpack-plugin/lib/runtime/components/react/mpx-keyboard-avoiding-view.tsx
- packages/webpack-plugin/lib/runtime/components/react/nav.tsx
1. MpxNav 和 keyboard-avoding 更改为从 mpxGlobal?.__mpx?.config?.rnConfig 上读取 rn 的配置
> fix: keyboard-avoding 从 mpx.config.rnConfig 中读取配置 
